# @format

version: "3.8"

services:
  adminer:
    image: adminer
    container_name: Adminer-Postgres
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgresdb
    ports:
      - 8080:8080
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chattodocker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      - DB_ENV=development-docker
    stdin_open: true
    tty: true

volumes:
  db:
