version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chattodocker
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
    ports:
      - "7500:5432"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    ports:
      - "1080:3000"
    environment:
      - DB_ENV=development-docker
    stdin_open: true
    tty: true

volumes: 
  db:
