version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: node_live_app
    ports:
      - "1080:3000"
    environment:
      - PG_DB=test-chatto
      - PG_USER=root
      - PG_PASSWORD=123
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "7500:5432"
    environment:
      - POSTGRES_DB=test-chatto
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}



